"""Generate analysis.json, SVG charts, Markdown report, and a lightweight DOCX report."""

from __future__ import annotations

import html
import json
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

from data_analysis import analyze, generate_charts


ROOT = Path(__file__).resolve().parent


def pct(item: dict) -> str:
    return f"{item['count']} ({item['percentage']:.1f}%)"


def table(title: str, values: dict[str, dict]) -> str:
    lines = [f"### {title}", "", "| Category | Count | Percentage |", "| --- | ---: | ---: |"]
    lines.extend(f"| {key} | {value['count']} | {value['percentage']:.1f}% |" for key, value in values.items())
    return "\n".join(lines)


def build_markdown(analysis: dict) -> str:
    categories = analysis["categories"]
    averages = analysis["feature_averages"]
    cross = analysis["cross_tabs"]
    models = analysis["models"]
    feature_rows = "\n".join(f"| {key} | {value:.2f}/5 |" for key, value in averages.items())
    exp_rows = "\n".join(f"| {key} | {v['respondents']} | {v['assistance_average']:.2f} | {v['ai_reliance_average']:.2f} | {v['comfort_average']:.2f} |" for key, v in cross["experience"].items())
    freq_rows = "\n".join(f"| {key} | {v['respondents']} | {v['comfort_average']:.2f} | {v['ai_reliance_average']:.2f} |" for key, v in cross["coding_frequency"].items())
    profile_rows = "\n".join(f"| {label.replace('_', ' ').title()} | {model['experience']} | {model['coding_frequency']} | {model['assistance_preference']} | {model['ai_reliance']}/5 | {model['comfort_without_ai']} |" for label, model in models.items())
    return f"""# CS 412 Second Laboratory Report

## From User Preferences to an Adaptive Coding Environment

**Data source:** `data/survey_data.xlsx` (the supplied workbook; 20 populated responses).  All counts, percentages, and averages below are generated by `data_analysis.py`. The attached PDF was not present in the workspace, so the pasted laboratory specification was used as the implementation brief.

## Section 1 - User Investigation

The investigation asks how programmers differ in experience, programming duration, coding frequency, languages, development environments, feature priorities, assistance preference, AI use, AI reliance, and comfort without AI. These characteristics matter because an adaptive coding environment must decide how much guidance to show, which tools to emphasize, and how intrusive suggestions should be.

The workbook contains {analysis['respondent_count']} actual respondent records. No respondent names or additional survey questions were created.

## Section 2 - Data Analysis

### Respondent count

The verified respondent count is **{analysis['respondent_count']}**.

{table('Programming experience', categories['experience'])}

{table('Programming duration', categories['duration'])}

{table('Coding frequency', categories['frequency'])}

{table('Most-used editor', categories['editor'])}

{table('Familiar development environments', categories['environments'])}

{table('Assistance preference scores', categories['assistance'])}

{table('AI usage', categories['ai_usage'])}

{table('AI use cases', categories['ai_use_cases'])}

{table('AI reliance', categories['ai_reliance'])}

{table('Comfort without AI', categories['comfort'])}

### Feature importance averages

| Feature | Average rating |
| --- | ---: |
{feature_rows}

### Experience comparison

| Experience | Respondents | Assistance average | AI reliance average | Comfort ordinal average |
| --- | ---: | ---: | ---: | ---: |
{exp_rows}

The comfort average is an analysis-only ordinal summary: Not comfortable = 1, Somewhat comfortable = 2, Very comfortable = 3. It is not treated as a continuous psychological measure.

### Coding-frequency comparison

| Coding frequency | Respondents | Comfort ordinal average | AI reliance average |
| --- | ---: | ---: | ---: |
{freq_rows}

### Observed findings and interpretations

**Observed:** All 20 respondents selected Yes for AI programming use. **Interpretation:** visible coding guidance is relevant to the prototype, but the application still keeps non-AI checking and debugging tools available.

**Observed:** Assistance scores include both 2 and 5, with intermediate values as well. **Interpretation:** a single always-on assistance level would not represent the variation in this sample.

**Observed:** The sample includes Beginner, Intermediate, and Advanced respondents and spans less than six months through 3+ years of programming. **Interpretation:** experience and duration are useful model attributes for a two-profile demonstration.

**Observed:** Feature ratings are mostly high, and the exact averages are listed above. **Interpretation:** error checking, debugging, and code execution can remain available in both profiles even when the visibility of routine assistance changes.

## Section 3 - User Model

The prototype uses only attributes that directly change behavior: experience, coding frequency, programming duration, assistance preference, AI reliance, comfort without AI, and feature priority. The model is deliberately small so each attribute has a visible effect.

| Attribute | Purpose in the prototype |
| --- | --- |
| Experience | Sets the context for beginner-oriented or compact explanations. |
| Coding frequency | Helps describe how often the modeled user encounters the tool. |
| Programming duration | Adds longitudinal context to experience. |
| Assistance preference | Controls hints, formatting, wrapping, and prompt visibility. |
| AI reliance | Controls whether offline coding guidance is primary or optional. |
| Comfort without AI | Controls feedback detail and beginner tips. |
| Feature priority | Keeps error detection, debugging, and execution visible. |

### Two actual respondent-derived profiles

| Profile | Experience | Coding frequency | Assistance | AI reliance | Comfort without AI |
| --- | --- | --- | --- | ---: | --- |
{profile_rows}

The Guided Builder is respondent 19 in the workbook; the Independent Builder is respondent 15. They are used as demonstration models, not as claims about every beginner or advanced programmer.

## Section 4 - Adaptation Rules

| User characteristic | System adaptation | Reason |
| --- | --- | --- |
| High assistance preference | Show detailed hints, autocomplete state, formatting, and explanations. | The selected model explicitly prefers high assistance. |
| Minimal assistance preference | Reduce routine prompts and disable automatic formatting. | The selected model prefers less intrusive help. |
| AI reliance of 4 or 5 | Make the clearly labeled offline Coding Guide action prominent. | AI reliance is a measured survey attribute, even though this prototype does not call an external AI service. |
| Low comfort without AI | Add more detailed error feedback and guided debugging tips. | The selected respondent reported Not comfortable. |
| All profiles | Keep syntax checking, debugging, and controlled execution available. | These are important features in the actual feature-rating responses. |

## Section 5 - Reflection

1. **Which characteristics were modeled, and why?** Experience, coding frequency, duration, assistance preference, AI reliance, comfort without AI, and feature priority were selected because they can change assistance visibility or tool emphasis.

2. **What patterns supported the model?** The workbook contains multiple experience levels, multiple durations, assistance scores from 2 through 5, and different AI reliance and comfort responses. The survey shows strong AI use, so the prototype makes guidance visible while remaining fully offline.

3. **How did the model influence behavior?** Switching profiles changes the active model display, editor wrapping, Format Code availability, AI button wording, feedback detail, and guidance text.

4. **What limitations does the model have?** The sample has only 20 responses. It is also concentrated toward frequent AI use and high feature ratings, which limits how confidently the prototype can generalize about non-AI workflows or low-feature-interest users. The two profiles are demonstration selections from individual rows rather than validated clusters.

5. **What additional information would help?** Task type, programming context, accessibility needs, language-specific workflows, and observed interaction behavior would make the model more useful. Repeated measures over time could also distinguish stable preference from a one-time response.

## Charts

Generated from the workbook by `generate_report.py`: experience, coding frequency, most-used editor, assistance preference, AI usage, AI reliance, and comfort without AI. The charts support the model decisions rather than replacing the tables.

## Demonstration procedure

1. Run `python generate_report.py` once to regenerate analysis artifacts.
2. Run `python main.py`.
3. Demonstrate Guided Builder first: Format Code is enabled, hints are prominent, and Coding Guide is primary.
4. Switch to Independent Builder: Format Code becomes disabled, editor wrapping becomes compact, and Coding Guide becomes optional while Check Code and Debug remain available.
5. Enter invalid Python and click Check Code to show that errors are handled without crashing.

## Submission checklist

- [x] 20 actual workbook responses verified.
- [x] Analysis, percentages, averages, and charts generated from the workbook.
- [x] Two combination-based respondent-derived user models.
- [x] Explicit adaptation rules.
- [x] Runnable Tkinter prototype with handled invalid code.
- [x] Offline Coding Guide clearly identified.
- [x] Five required report sections and reflection.
"""


def _docx_xml(markdown: str) -> tuple[str, str]:
    body = []
    for line in markdown.splitlines():
        if not line.strip():
            continue
        if line.startswith("# "):
            style = "Title"
        elif line.startswith("## "):
            style = "Heading1"
        elif line.startswith("### "):
            style = "Heading2"
        else:
            style = "Normal"
        text = line.lstrip("# ")
        if text.startswith("|"):
            text = text.replace("|", " ").replace("---", "")
        body.append(f'<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr><w:r><w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:p>')
    document = f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>{"".join(body)}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>'
    styles = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:sz w:val="22"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:sz w:val="40"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:sz w:val="30"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="Heading 2"/><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b/><w:sz w:val="24"/></w:rPr></w:style></w:styles>'
    return document, styles


def write_docx(markdown: str, path: Path) -> None:
    document, styles = _docx_xml(markdown)
    rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'
    document_rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>'
    content_types = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>'
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types)
        archive.writestr("_rels/.rels", rels)
        archive.writestr("word/document.xml", document)
        archive.writestr("word/styles.xml", styles)
        archive.writestr("word/_rels/document.xml.rels", document_rels)


def main() -> None:
    data_dir = ROOT / "data"
    report_dir = ROOT / "report"
    charts_dir = ROOT / "charts"
    data_dir.mkdir(exist_ok=True)
    report_dir.mkdir(exist_ok=True)
    analysis = analyze(data_dir / "survey_data.xlsx")
    (data_dir / "analysis.json").write_text(json.dumps(analysis, indent=2), encoding="utf-8")
    generate_charts(analysis, charts_dir)
    markdown = build_markdown(analysis)
    (report_dir / "laboratory_report.md").write_text(markdown, encoding="utf-8")
    write_docx(markdown, report_dir / "laboratory_report.docx")
    print(f"Generated report artifacts for {analysis['respondent_count']} verified responses.")


if __name__ == "__main__":
    main()
